### PR TITLE
[PF-1922] Apply Formatting to repo: terra-cli

### PR DESCRIPTION
**Pull request by dexamundsen**
Apply formatting to entire repo (no manual changes)

### CODE REVIEW

**Comment by yuhuyoyo** [comment]
Could you kindly figure out why the lint check is not working?

**Comment by mikenev** [comment]
What's driving this change? We do have spotless and the lint check, was it not applying rules or something?

**Comment by dexamundsen** [comment]
@mikenev - looks like the google java format was not applied on the IDE. I applied this as part of JDK upgrade and lead to a whole lot of format changes. Hence split it to a separate PR
@yuhuyoyo - Fixed the check. There is an issue with single line comments: the rules for google java format and spotless check were conflicting

**Review by mikenev — APPROVED** [review]
Ok, that makes sense. Thanks for doing this in a separate review.

**Review by yuhuyoyo — APPROVED** [review]
this is impossible to review so i will just trust you :)

**Comment by yuhuyoyo** [comment]
filed https://broadworkbench.atlassian.net/browse/PF-1924

**Pull request merged**
