### PR TITLE
fix typo, make the ssh-key command descriptive text more consistent

### PR DESCRIPTION
**Pull request by amygdala**
I created the PR to fix a typo in a description, but while I was in there I thought I would make the descriptive text a bit more consistent as well.

### CODE REVIEW

**Comment by amygdala** [comment]
None of my changes were actual code changes (I just changed description strings), and I don't believe the test failures are related.

**Review by wnojopra — APPROVED** [review]
lgtm. Thanks!

**Comment by amygdala** [comment]
@yuhuyoyo , would you be willing to approve this small PR as well? (I don't believe the failing tests are related to my changes and am hoping they will resolve soon).

**Review by yuhuyoyo — APPROVED** [review]

**Comment by amygdala** [comment]
thanks @wnojopra and @yuhuyoyo !

**Pull request merged**
