### PR TITLE
[PF-2167] Add new verily environments

### PR DESCRIPTION
**Pull request by dexamundsen**
Add new verily environments - mc-dev and mc-flagged

### CODE REVIEW

**Comment by yuhuyoyo** [comment]
what does mc-flagged mean?

**Comment by dexamundsen** [comment]
> what does mc-flagged mean?

- mc-dev: development environment
- mc-flagged: development environment with all features blocked via a feature flag. for end users this should look the same as the regular dev / staging environment. The main goal of having this is to ensure we dont break any other existing functionality

**Comment by yuhuyoyo** [comment]
what's the benefit of having another environment vs just having the dev and you can switch flags on-off?

less deployment overhead and more flexibility (e.g. having a subset of flags on)

**Comment by dexamundsen** [comment]
> what's the benefit of having another environment vs just having the dev and you can switch flags on-off?
> 
> less deployment overhead and more flexibility (e.g. having a subset of flags on)

The general idea is -(from deployment design doc) 
Integration tests run against a “dev” environment that enables new features, and a “flagged off” environment that disables new functionality via feature flags/config parameters to expose regressions in existing code paths caused by our changes.

**Comment by yuhuyoyo** [comment]
That is a valuable testing feature (i listed it under nice to have in the feature requirement doc but I guess I should move it up :) ) I wasn't able to find any documentation for out-of-box testing framework support for this.

WSM integration test set config for different environments like this https://github.com/DataBiosphere/terra-workspace-manager/tree/main/integration/src/main/resources/configs/integration. Say we are using LD. Can we instead create an all-flagged-on environment and all-flagged-off environment in LD and have the test points to their client ids (different per environment)?

**Comment by dexamundsen** [comment]
> That is a valuable testing feature (i listed it under nice to have in the feature requirement doc but I guess I should move it up :) ) I wasn't able to find any documentation for out-of-box testing framework support for this.
> 
> WSM integration test set config for different environments like this https://github.com/DataBiosphere/terra-workspace-manager/tree/main/integration/src/main/resources/configs/integration. Say we are using LD. Can we instead create an all-flagged-on environment and an all-flagged-off environment in LD and have the test points to their client ids (different per environment)?
> 
> or just separate config files when there's no feature flagging yet

Agree on the alternate to accomplishing this. However since the MC design and implementation may have near-term changes, created this second env.  This flagged env will essentially be removed later once the concept of feature flagging is set up for all services as needed. In the meantime, this is the easiest path to getting there (we don't have feature flags or configs set up on all services in the manner we need). Happy to plan the EOL of this env once we have it set up.

**Review by zloery — APPROVED** [review]

**Pull request merged**
